services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/client/Dockerfile
    ports:
      - '4200:4200'
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.backend
    ports:
      - '8081:8081'
    env_file:
      - .env
    environment:
      MONGO_URI: 'mongodb://mongo:27017/protasker'
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
