name: CI for ProTasker (Local Deployment)

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend/client

      - name: Run tests
        run: npm run test -- --code-coverage --browsers=ChromeHeadlessNoSandbox --watch=false
        working-directory: ./frontend/client

      - name: Lint code
        run: npm run lint
        working-directory: ./frontend/client

      - name: Build Angular App
        run: npm run build
        working-directory: ./frontend/client

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: dist/client/
